- name: nvim
  source: /home/sumit/easypeasy/dotfiles/nvim
  status: Linked
  target: /home/sumit/.config/nvim
- name: mpv
  source: /home/sumit/easypeasy/dotfiles/mpv
  status: Linked
  target: /home/sumit/.config/mpv
- name: btop
  source: /home/sumit/easypeasy/dotfiles/btop
  status: Linked
  target: /home/sumit/.config/btop
- name: fish
  source: /home/sumit/easypeasy/dotfiles/fish
  status: Linked
  target: /home/sumit/.config/fish
- name: ghostty
  source: /home/sumit/easypeasy/dotfiles/ghostty
  status: Linked
  target: /home/sumit/.config/ghostty
- name: fastfetch
  source: /home/sumit/easypeasy/dotfiles/fastfetch
  status: Linked
  target: /home/sumit/.config/fastfetch
- name: alacritty
  source: /home/sumit/easypeasy/dotfiles/alacritty
  status: Linked
  target: /home/sumit/.config/alacritty
- name: hyprpanel
  source: /home/sumit/easypeasy/dotfiles/hyprpanel
  status: Linked
  target: /home/sumit/.config/hyprpanel
- name: ohmyposh
  source: /home/sumit/easypeasy/dotfiles/ohmyposh
  status: Linked
  target: /home/sumit/.config/ohmyposh
- name: yazi
  source: /home/sumit/easypeasy/dotfiles/yazi
  status: Linked
  target: /home/sumit/.config/yazi
- name: zed
  source: /home/sumit/easypeasy/dotfiles/zed
  status: Linked
  target: /home/sumit/.config/zed
- name: nushell
  source: /home/sumit/easypeasy/dotfiles/nushell
  status: Linked
  target: /home/sumit/.config/nushell
- name: HyprUserPref
  source: /home/sumit/easypeasy/dotfiles/userprefs.conf
  status: Linked
  target: /home/sumit/.config/hypr/userprefs.conf
