name: Build and Release Linux Binaries

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Nuitka
        run: pip install nuitka

      - name: Build easydots
        run: |
          python -m nuitka \
            --onefile \
            --standalone \
            --output-dir=build \
            --assume-yes-for-downloads \
            easydots.py

      - name: Verify build files
        run: ls -lR build # Debugging step to check file structure

      - name: Create compressed archives
        run: |
          mkdir -p dist
          tar -cJf dist/easydots-linux.tar.xz -C build/easydots.dist easydots
          tar -cJf dist/easyscripts-linux.tar.xz -C build/easyscripts.dist easyscripts

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.tar.xz
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
