name: Build Python Binary with Nuitka

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write # Grants permission to create a GitHub release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip install -r requirements.txt
          pip install nuitka

      - name: Build `easydots.py` Binary
        run: |
          mkdir -p build
          nuitka --follow-imports --standalone --output-dir=build easydots.py

      - name: Build `easyscripts.py` Binary
        run: |
          nuitka --follow-imports --standalone --output-dir=build easyscripts.py

      - name: Debug List Build Directory
        run: ls -R build/

      - name: Package Binaries into tar.xz
        run: |
          tar --warning=no-file-changed -cJf build/easymanager.tar.xz -C build .
          ls -lh build/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binaries
          path: build/easymanager.tar.xz

  release:
    needs: build # Waits for the build job to complete
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Compiled Binaries
        uses: actions/download-artifact@v4
        with:
          name: compiled-binaries
          path: build/

      - name: List Downloaded Files
        run: ls -lh build/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/easymanager.tar.xz # Uploads the tar.xz archive
          tag_name: v1.0.3 # Change dynamically if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
