name: Build Python Binary with Nuitka

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka

      - name: Build `easydots.py` Binary
        run: |
          mkdir -p build
          nuitka --follow-imports --standalone --output-dir=build easydots.py

      - name: Build `easyscripts.py` Binary
        run: |
          nuitka --follow-imports --standalone --output-dir=build easyscripts.py

      - name: Debug – List Build Directory
        run: ls -R build/

      - name: Package Binaries into tar.xz
        run: |
          mkdir -p dist/easymanager
          cp -r build/easydots.dist dist/easymanager/easydots
          cp -r build/easyscripts.dist dist/easymanager/easyscripts
          tar -cJf dist/easymanager.tar.xz dist/easymanager
          ls -lh dist/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binaries
          path: dist/easymanager.tar.xz

  release:
    needs: build # Waits for the build job to complete
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Compiled Binaries
        uses: actions/download-artifact@v4
        with:
          name: compiled-binaries
          path: dist/

      - name: List Downloaded Files
        run: ls -lh dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/easymanager.tar.xz # Use the correct path to the archive
          tag_name: v1.0.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
