name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Nuitka
        run: |
          python -m pip install --upgrade pip
          pip install nuitka

      - name: Build `easydots.py` Binary
        run: |
          mkdir -p build
          python -m nuitka --onefile --output-dir=build --output-filename=easydots.bin easydots.py

      - name: Build `easyscripts.py` Binary
        run: |
          python -m nuitka --onefile --output-dir=build --output-filename=easyscripts.bin easyscripts.py

      - name: Debug List Built Files
        run: ls -lh build/

      - name: Upload Binaries as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binaries
          path: |
            build/easydots.bin
            build/easyscripts.bin

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Binaries
        uses: actions/download-artifact@v4
        with:
          name: compiled-binaries
          path: ./dist

      - name: Debug List Downloaded Files
        run: ls -lh ./dist/

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload `easydots.bin` to Release
        uses: actions/upload-release-asset@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/easydots.bin
          asset_name: easydots.bin
          asset_content_type: application/octet-stream

      - name: Upload `easyscripts.bin` to Release
        uses: actions/upload-release-asset@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/easyscripts.bin
          asset_name: easyscripts.bin
          asset_content_type: application/octet-stream
